# vim ft=yaml
# travis-ci.org definition

sudo: true
dist: trusty

git:
  depth: 2

language: cpp
os:
  - linux
  - osx
osx_image: xcode9.1
compiler:
  - gcc
  - clang

cache:
  apt: true
  ccache: true # Does not currently work for clang builds: https://github.com/travis-ci/travis-ci/issues/6201
  directories:
    - /usr/local/Cellar # Fails do to permission error: https://github.com/travis-ci/travis-ci/issues/8092

env:
  matrix:
    - GCC_VERSION=4.8 TYPE=RelWithDebInfo MYSQL_TEST_SUITES=rpl
    - GCC_VERSION=5   TYPE=RelWithDebInfo MYSQL_TEST_SUITES=main,archive,optimizer_unfixed_bugs,parts,sys_vars,unit,vcol,innodb,innodb_gis,innodb_zip,innodb_fts
    - GCC_VERSION=6   TYPE=RelWithDebInfo MYSQL_TEST_SUITES=binlog,binlog_encryption,encryption,rocksdb
    - GCC_VERSION=6   TYPE=RelWithDebInfo MYSQL_TEST_SUITES=csv,federated,funcs_1,funcs_2,gcol,handler,heap,json,maria,perfschema,plugins,multi_source,roles

matrix:
  exclude:
    - os: osx
      compiler: gcc
  include:
    - os: linux
      compiler: gcc
      env:
        - DebPackages
      addons:
        apt:
          packages: # make sure these match debian/control contents
            - bison
            - chrpath
            - cmake
            - debhelper
            - dh-apparmor
            - dpatch
            - gdb
            - libaio-dev
            - libboost-dev
            - libcurl3-dev
            - libdbd-mysql
            - libjudy-dev
            - libncurses5-dev
            - libpam0g-dev
            - libpcre3-dev
            - libreadline-gplv2-dev
            - libstemmer-dev
            - libssl-dev
            - libnuma-dev
            - libxml2-dev
            - lsb-release
            - perl
            - po-debconf
            - psmisc
            - zlib1g-dev
            - libcrack2-dev
            - cracklib-runtime
            - libjemalloc-dev
            - libsnappy-dev
            - liblzma-dev
            - libzmq-dev
            - libdistro-info-perl
            - uuid-dev
            - devscripts
            - fakeroot
      script:
        - ${CC} --version ; ${CXX} --version
      # https://github.com/travis-ci/travis-ci/issues/7062 - /run/shm isn't writable or executable
      # in trusty containers
        - export MTR_MEM=/tmp
        - env DEB_BUILD_OPTIONS="parallel=6" debian/autobake-deb.sh;
        - ccache --show-stats
  # Until OSX becomes a bit more stable: MDEV-12435
  allow_failures:
    - os: osx
      compiler: clang
      env: GCC_VERSION=4.8 TYPE=RelWithDebInfo MYSQL_TEST_SUITES=rpl
    - os: osx
      compiler: clang
      env: GCC_VERSION=5   TYPE=RelWithDebInfo MYSQL_TEST_SUITES=main,archive,optimizer_unfixed_bugs,parts,sys_vars,unit,vcol,innodb,innodb_gis,innodb_zip,innodb_fts
    - os: osx
      compiler: clang
      env: GCC_VERSION=6   TYPE=RelWithDebInfo MYSQL_TEST_SUITES=binlog,binlog_encryption,encryption,rocksdb
    - os: osx
      compiler: clang
      env: GCC_VERSION=6   TYPE=RelWithDebInfo MYSQL_TEST_SUITES=csv,federated,funcs_1,funcs_2,gcol,handler,heap,json,maria,perfschema,plugins,multi_source,roles

before_install:
  - if [[ "${TRAVIS_OS_NAME}" == 'osx' ]]; then
      brew update;
      brew install gnutls lz4 lzo xz snappy ccache jemalloc curl ossp-uuid pcre;
      brew link ccache;
    fi

script:
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
      ./.travis.test.sh;
    else
       docker login registry.shel.nu:5000 --username mariadb --password builddeps;
       docker run -e CC=${CC} -e CXX=${CXX} -e TRAVIS_OS_NAME=${TRAVIS_OS_NAME} -e GCC_VERSION=${GCC_VERSION} -e TYPE=${TYPE} -e MYSQL_TEST_SUITES=${MYSQL_TEST_SUITES} -v $PWD:/opt/server -t registry.shel.nu:5000/mariadb/mariadb-build-deps /opt/server/.travis.test.sh;
    fi

#  #notifications:
#  irc:
#    channels:
#      - "chat.freenode.net#maria"
#    on_success: never # [always|never|change]
#    on_failure: never
#    template:
#      - "%{repository}/%{branch} (%{commit} - %{author}): %{build_url}: %{message}"
